#SERVER CONFIG
server:
  port: 8090
# KEYCLOACK CONFIGURATIONS
app:
  config:
    keycloak:
      url: http://localhost:8080
      realm: pms
      client-secret: oUVnjjhjlOYoCxb2DlrhHFxXL7JKgNUW
      client-id: pms-client

# API SECURITY WITH KEYCLOAK PROVIDER
# spring:
#   security:
#     oauth2:
#       client:
#         provider:
#           keycloak:
#             authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
#             jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
#             token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
#             user-info-authentication-method: header
#             user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
#             user-name-attribute: preferred_username
#         registration:
#           internet-banking-core-client:
#             authorization-grant-type: authorization_code
#             client-id: ${app.config.keycloak.client-id}
#             client-secret: ${app.config.keycloak.client-secret}
#             provider: keycloak
#             redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
#             scope: openid
#       resourceserver:
#         jwt:
#           jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs

#EUREKA CLIENT CONFIG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8093/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true



  #LOGGING
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      reactor.netty.http.client: DEBUG



