server:
  port: 8093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8093/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: localhost
